apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookverse-prod
  namespace: argocd
spec:
  description: BookVerse PROD environment
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

