apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookverse-staging
  namespace: argocd
spec:
  description: BookVerse STAGING environment
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

